// <auto-generated />
using BudgetTrackerReactServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetTrackerReactServer.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220916081214_FirstTransactionMigration")]
    partial class FirstTransactionMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("BudgetTrackerReactServer.Data.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<float>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("TransactionId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Note = "Transaction number1",
                            Value = 1f
                        },
                        new
                        {
                            TransactionId = 2,
                            Note = "Transaction number2",
                            Value = 2f
                        },
                        new
                        {
                            TransactionId = 3,
                            Note = "Transaction number3",
                            Value = 3f
                        },
                        new
                        {
                            TransactionId = 4,
                            Note = "Transaction number4",
                            Value = 4f
                        },
                        new
                        {
                            TransactionId = 5,
                            Note = "Transaction number5",
                            Value = 5f
                        },
                        new
                        {
                            TransactionId = 6,
                            Note = "Transaction number6",
                            Value = 6f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
